name: 'datawatch'
version: '1.0.0'
config-version: 2

profile: 'datawatch'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  datawatch:
    +materialized: view
