datawatch:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'postgres') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'postgres') }}"
      port: 5432
      dbname: "{{ env_var('DB_NAME', 'postgres') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
